export const TEAM_FLAG_CODE: Record<string, string> = {
  'Canadá': 'ca',
  'Estados Unidos': 'us',
  'México': 'mx',
  'Panamá': 'pa',
  'Haití': 'ht',
  'Curazao': 'cw',
  'Japón': 'jp',
  'Nueva Zelanda': 'nz',
  'Irán': 'ir',
  'Uzbekistán': 'uz',
  'Corea del Sur': 'kr',
  'Jordania': 'jo',
  'Australia': 'au',
  'Arabia Saudita': 'sa',
  'Catar': 'qa',
  'Argentina': 'ar',
  'Brasil': 'br',
  'Ecuador': 'ec',
  'Uruguay': 'uy',
  'Colombia': 'co',
  'Paraguay': 'py',
  'Marruecos': 'ma',
  'Túnez': 'tn',
  'Egipto': 'eg',
  'Argelia': 'dz',
  'Ghana': 'gh',
  'Cabo Verde': 'cv',
  'Sudáfrica': 'za',
  'Costa de Marfil': 'ci',
  'Senegal': 'sn',
  'R. D. del Congo': 'cd',
  'Inglaterra': 'gb-eng',
  'Francia': 'fr',
  'Croacia': 'hr',
  'Portugal': 'pt',
  'Noruega': 'no',
  'Alemania': 'de',
  'Países Bajos': 'nl',
  'Bélgica': 'be',
  'Austria': 'at',
  'Suiza': 'ch',
  'España': 'es',
  'Escocia': 'gb-sct',
  'Suecia': 'se',
  'Turquía': 'tr',
  'Rep. Checa': 'cz',
  'Bosnia y Herz.': 'ba',
  'Irak': 'iq',
}

export function flagUrl(teamName: string): string | null {
  const code = TEAM_FLAG_CODE[teamName]
  return code ? `https://flagcdn.com/w80/${code}.png` : null
}
